### ISSUE TITLE
Venezuelan taxcode Regex (BUG)

### ISSUE THREAD

**Issue by mmmarcolino** [maielo/stripe-tax-utils#7]
https://github.com/maielo/stripe-tax-utils/blob/7aa2eb32090a1215cb0b71e264a1a21f9e71a6cc/src/stripeTaxMap.ts#L647

The Venezuelan tax-code regex accepts only tax-code starting with 'A' while it should accept every capital letter '[A-Z]'.

Perhaps this tax-code 'J-12354768-9' should be accepted as a valid Venezuelan tax-code (as far as I know) but it doesn't.

Thanks for your help in advance.

**Comment by mmmarcolino** [comment]
Cfr. https://www.zim.com/za-cn/news/shipping-news-regulations/venezuelan-rif-number

**Comment by maielo** [comment]
From this link:  "The number consists of an E, I, J, or V, followed by an eight-digit number and a check digit, all separated by hyphens. For example: V-12345678-0." So only letters E,I,J or V are allowed. Current regex assumes only A which is wrong. Going to fix it

**Comment by mmmarcolino** [comment]
Indeed the starting J is not accepted...
I do not get the point of your answer; a valid Venezuelan tax-code starting with 'J' won't be accepted by your regex

**Comment by mmmarcolino** [comment]
Thanks, for your work and for fixing this, thanks a lot! 
I appreciate it! 
:)

**Comment by maielo** [comment]
Fixed and published
